### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by steinerkelvin** [paed01/bpmn-engine-extensions#1]
Running the [Camunda ServiceTask example](https://github.com/paed01/bpmn-engine-extensions/blob/master/docs/Examples.md#camunda-servicetask) is giving me a `Error: extensions[camunda] is not a function` error:

```
      if (typeof input.extensions[key] !== 'function') throw new Error(`extensions[${key}] is not a function`);
                                                       ^

Error: extensions[camunda] is not a function
    at validateOptions (/home/kelvin/pop-workspace/bpmn-engine-test/node_modules/bpmn-elements/dist/src/Environment.js:143:62)
    at Object.Environment (/home/kelvin/pop-workspace/bpmn-engine-test/node_modules/bpmn-elements/dist/src/Environment.js:17:26)
    at Engine (/home/kelvin/pop-workspace/bpmn-engine-test/node_modules/bpmn-engine/index.js:39:30)
    at Object.<anonymous> (/home/kelvin/pop-workspace/bpmn-engine-test/test.js:34:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by paed01** [comment]
Sorry about that. This repo has been inactive for a while while the engine has moved substantially forward. If you are looking for how to extend the engine please have a look [here](/paed01/bpmn-engine/blob/master/docs/Examples.md#extend-form-behaviour) and [here](/paed01/bpmn-elements/blob/master/docs/Extension.md) or reactivate this repo by a PR.
